spring:
  application:
    name: vectordb

  # data source configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # OpenAI API key
      openai:
        chat:
          model: gpt-4
        embedding:
          model: text-embedding-ada-002

server:
  port:
    8080

embedding:
  generation:
    skip: ${EMBEDDING_GENERATION_SKIP:true}
